// H2: the text `/pr-review` answers questions about itself with.
//
// It lives here rather than in `extension.mjs` because that module calls
// `joinSession` at the top level, so importing it starts a session and no
// controlled suite can read a line of this text. Three false user-facing
// strings have shipped in it for exactly that reason. Here `smoke-help.mjs`
// reads both constants directly, for free, on every CI run.
// The answer to "I want to review a pull request, what are my options?". It is
// what `help` prints, so it is the first thing anybody reads: the modes, then
// the options grouped by the decision each one makes, then the lifecycle
// commands. Everything it leaves out is one command away, and `smoke-help.mjs`
// holds it to a line budget so it cannot grow back into the reference below.
export const helpOrientation = [
  "Review a pull request with Copilot. Reviews use Copilot credits.",
  "",
  "  /pr-review NUMBER [mode] [options]",
  "",
  "MODES (pick one; --balanced is the default)",
  "  --quick         Three heavy specialists, P0-P2 findings only.",
  "  --balanced      Four specialists plus an overview reviewer; P0-P2 plus at most three minor.",
  "  --full          Adds a conventions/maintainability reviewer; every severity, no minor cap.",
  "  --deep          One integrated reviewer over the whole change instead of specialists.",
  "  --capture-only  Capture and bind the target, then stop. No reviewers, no credits.",
  "",
  "OPTIONS",
  "  Publishing   --comment authorizes posting, --no-comment suppresses it, and --all selects",
  "               every validated finding. Selecting a finding never authorizes posting it.",
  "  Scope        --incremental confines fresh hunting to the commits added since an earlier",
  "               review, --revalidate judges what became of that review's findings,",
  "               --no-standards stops handing this project's own rules to the reviewer,",
  "               --include-drafts and --include-closed widen what may be captured.",
  "  Safety       --verify adds the stricter preflight and offers this project's safeguards,",
  "               --unattended refuses up front any run that would need somebody present.",
  "  Output       --quiet prints less of the same review, never less of what makes it",
  "               trustworthy: coverage, refusals and publication outcomes always print.",
  "  Models       --long-context asks each model for its long-context window, at its own",
  "               price; heavyModel=ID and heavyEffort=LEVEL set the heavy tier for one run.",
  "",
  "COMMANDS",
  "  status   What this plugin implements.   models    What your subscription offers.",
  "  inspect  This session's retained result. publish   Publish that retained selection.",
  "  cancel   Stop active review work and its runtime.",
  "  /pr-review-config   Saved model tiers, fallbacks, autoPostReviews, project trust.",
  "",
  "Reviewers also read your checkout, which must be the reviewed revision:",
  "run `gh pr checkout NUMBER` first, with nothing modified or staged.",
  "",
  "Full reference, with every flag, gate and rule: /pr-review help --all",
].join("\n");

export const helpReference = [
  "Copilot PR Review - full reference",
  "",
  "Usage: /pr-review [status|help|models|fixture model1=ID effort1=LEVEL model2=ID effort2=LEVEL]",
  "       /pr-review NUMBER [--balanced|--full|--deep|--quick|--major-only] [--comment|--no-comment] [--all]",
  "                         [--verify] [--quiet] [--unattended] [--incremental] [--revalidate]",
  "                         [--long-context] [--no-standards]",
  "                         [--include-drafts] [--include-closed|--review-closed]",
  "                         [heavyModel=ID] [heavyEffort=LEVEL]",
  "       /pr-review NUMBER --capture-only [--include-drafts] [--include-closed|--review-closed]",
  "",
  "status  Show the implemented capability boundary (default).",
  "help    Show this usage information.",
  "models  List available subscription models and supported reasoning efforts.",
  "fixture Run two reviewers of the bundled original fixture (uses Copilot credits).",
  "adversarial  Same settings; exercise forbidden tools and untrusted fixture text.",
  "failure      Same settings; inject a failure in the first active reviewer.",
  "cancel       Cancel active review work and stop its owned runtime.",
  "inspect      Show this session's latest retained result without inference or GitHub requests.",
  "publish      Explicitly publish this session's retained selected findings without rerunning reviewers.",
  "",
  "Configuration: /pr-review-config [show] | key=value ... | unset key ... | trust | untrust [PATH] | help.",
  "Saved tiers supply unset assignments; a trusted project's file overrides them; invocation flags win.",
  "Each tier may carry one optional fallback model, used for at most one extra attempt after a reviewer's",
  "own explicit failure. Reviews have no timeout, so elapsed time alone never triggers one.",
  "An untrusted repository's .copilot/pr-review/config.json is ignored; a repository cannot trust itself.",
  "",
  "NUMBER  Capture PR metadata and diff, bind source context to the captured head/base",
  "        revisions, then run the selected review mode. Reviews use Copilot credits.",
  "Drafts and obvious bots are skipped, as are provably empty changes.",
  "Closed/merged PRs require confirmation or an explicit closed-PR override.",
  "--balanced  Four heavy specialists (correctness, contracts, security, performance/resources)",
  "            plus one light overview reviewer. This is the default when no mode flag is given.",
  "--full      The balanced reviewers plus one medium conventions/maintainability reviewer.",
  "--deep      One integrated heavy reviewer over the whole pull request, instead of parallel",
  "            specialists. Holistic review, not a larger parallel one and not a higher effort.",
  "--quick / --major-only  Three heavy specialists on captured PR content.",
  "Mode flags are mutually exclusive.",
  "Balanced presents P0-P2 findings plus at most three P3/nit findings anchored on changed lines;",
  "full and deep present every substantiated severity with no minor cap; quick presents P0-P2 only.",
  "Withheld minor findings are reported, never silently dropped.",
  "--verify  Opt into the stricter preflight before any reviewer starts: the current branch must be the",
  "          PR's head branch, and no path may be untracked, in addition to the checks every review makes.",
  "          Once it passes, the root instruction files of this checkout are read and the safeguard commands",
  "          they declare are presented with the file each came from. You are then asked which of them may",
  "          run, and an approved command runs in this checkout, as you, before any reviewer starts. That",
  "          question is the only thing that approves one, and the answer does not outlive the run. No",
  "          reviewer receives a command or its output, so a safeguard grounds no finding and a failing one",
  "          leaves this review's own coverage alone; a passing preflight is still an ordinary review of the",
  "          selected mode. It is orthogonal to the mode and posting flags, cannot be combined with --capture-only,",
  "          and is not a configuration key: no saved or trusted-project setting can turn verification on.",
  "--quiet   Print less of the same review: the evidence JSON lines (the target, the context, the mode's",
  "          binding, the settled run, the selection) and each reviewer's raw untrusted output, including",
  "          the adjudicator's, are left out. Everything that decides whether the result can be trusted",
  "          stays at every verbosity: the effective assignments, per-reviewer progress, every refusal and",
  "          failure, the coverage report and its diagnostics, the safeguard discovery, approval and",
  "          execution summaries, the findings, and every publication outcome including an uncertain write.",
  "          Verbose is the default and a run without the flag prints exactly what it printed before. The",
  "          flag changes presentation only: the same review settles the same way and the retained record",
  "          still holds every reviewer's own output. It authorizes nothing, opens no gate, and is not a",
  "          configuration key, so no saved or trusted-project setting can quieten a run. It cannot be",
  "          combined with --capture-only, whose entire output is the evidence it would suppress.",
  "A finished review reports what it cost on one line beside its coverage: the credit total the runtime",
  "        reported, the model time its passes spent, and the time the run took. Every pass it paid for is",
  "        counted, including the safeguard discovery pass, the revalidation pass and a failed attempt a",
  "        fallback replaced. One request the runtime reported no charge for leaves the total unavailable",
  "        rather than a partial sum, because an unreported charge is unknown and not zero. A run that",
  "        failed or was cancelled still reports what it spent, and --quiet never suppresses the line.",
  "--unattended  Declare that this run leaves no question for anybody to answer, for a headless environment,",
  "          a CI pipeline or an autonomous loop. It is checked before the target is captured and before any",
  "          credit is spent, and it refuses rather than proceeds: a run without --all is refused, because",
  "          finding selection is a question and --all is the only thing that settles it without a person;",
  "          a run without --comment or --no-comment is refused, so what this run may publish is visible in",
  "          the invocation rather than in a saved setting; and a run with --verify is refused, because a",
  "          safeguard command is approved by the question an unattended run cannot ask and by nothing else.",
  "          A closed or merged PR is not confirmed either, so it stops at capture unless --include-closed or",
  "          --review-closed was given. The flag authorizes nothing and opens no gate: --all still authorizes",
  "          no posting, every publication gate still runs, and it is not a configuration key, so no saved or",
  "          trusted-project setting can turn it on. It cannot be combined with --capture-only.",
  "--revalidate  Judge what became of the findings an earlier review of this pull request published, where",
  "          this tool cannot prove it for free. Every review already reports the verdicts it can prove: a",
  "          comment on lines the newer commits never touched is still open, and one GitHub can no longer",
  "          place, or whose file those commits deleted, is obsolete. What none of that settles needs the",
  "          current code read, so this flag buys one model pass over exactly those findings and nothing",
  "          else. It reports no new finding, is never asked about a verdict the code proved, and can never",
  "          overturn one. A pass that fails settles nothing and loses nothing. A settled verdict is posted",
  "          as a reply on the thread the earlier review left, under the same posting authority as the review",
  "          itself: --no-comment suppresses both, a confirmed proposal covers both, and a declined one refuses",
  "          both. A run that publishes no review has no proposal to confirm, so its replies ask for",
  "          themselves. A thread already carrying",
  "          this run's answer at this head is skipped rather than answered twice. It cannot be combined with",
  "          --capture-only.",
  "--incremental  Ask for fresh hunting to be confined to the commits added since an earlier review of this",
  "          pull request by this tool, so a re-review stops reporting hunks that review already covered.",
  "          It is a request rather than a parse-time contract, and the only flag that is: whether a forward",
  "          commit range exists at all is a fact about the pull request. When capture reports the relationship",
  "          as incremental, those commits' head-side line ranges become the confined scope; on any other",
  "          relationship, when the range cannot be read, or when those commits change no file, the run",
  "          narrows nothing and says which of those it was. Confinement is a filter over the captured",
  "          base-to-head binding and never a replacement for it: the captured diff, the context windows, the",
  "          provenance checks and every citation rule are exactly what an unconfined run uses. A candidate",
  "          anchored outside the range is set aside as already covered, reported with its location rather",
  "          than dropped, and never adjudicated, so it is neither a validated finding nor a refuted one; a",
  "          base-side anchor cannot be placed in the range, so one in a file those commits did touch stays",
  "          in scope. A confined review does not cover the whole pull request, and says so in the run and in",
  "          the published review body: what it did not hunt was covered by the earlier review, whose own",
  "          coverage this run does not read and does not vouch for. That is why it is opt-in rather than the",
  "          default. It authorizes nothing, opens no gate, and is not a configuration key, so no saved or",
  "          trusted-project setting can confine a run. It cannot be combined with --capture-only.",
  "--long-context  Ask every model pass this review starts for its model's long-context window, so a large",
  "          pull request is less likely to be compacted. That window is billed at its own price, which the",
  "          runtime has listed at up to twice the default input price. A model that lists no long-context",
  "          window runs on its own window instead of refusing the review, and the assignments say so before",
  "          any reviewer starts. A model that lists one and does not keep it is refused; nothing is",
  "          substituted. Each pass says which window it asked for. The runtime confirms that the request was",
  "          kept, not that inference used the larger window. It authorizes nothing, is not a configuration",
  "          key, so nothing saved can turn it on, and it cannot be combined with --capture-only.",
  "--no-standards  Turn off, for this run only, what every review otherwise does: hand the markdown files at the",
  "          checkout root that are the reviewed head's committed text, up to a 48 KiB budget that takes agent",
  "          files first, to the one reviewer that weighs the whole change (overview in balanced and full,",
  "          integrated in deep, contracts in quick). That reviewer may",
  "          report changed lines that break or contradict one of those rules by quoting the rule as exact lines",
  "          of its file, and code refuses a quote it cannot find there. Every run names each file it handed on",
  "          and each it left out, with the reason. With the flag no reviewer is handed a file and no finding may",
  "          rely on one. It authorizes nothing, is not a configuration key, and cannot be combined with",
  "          --capture-only.",
  "--capture-only  Capture and bind the target, then stop: no reviewers, no inference, no publication.",
  "Reviewers additionally read this checkout, so it must be the reviewed revision:",
  "local HEAD must equal the captured PR head, the PR head must not have moved, and no tracked",
  "file may be modified or staged. Otherwise the review is refused; run `gh pr checkout NUMBER` first.",
  "A --verify run adds the head branch and the untracked-path conditions to that same gate. No refusal is",
  "ever repaired automatically: nothing is switched, pulled, stashed or cleaned to satisfy any of them.",
  "Reviewers get view/grep/glob confined to the checkout; every other tool stays unavailable.",
  "Each reviewer resolves its mode's tier: heavy specialists, light overview, medium conventions,",
  "and deep's single integrated reviewer on the heavy tier.",
  "Unset tiers inherit the nearest configured tier, then the ambient model/effort. Only",
  "heavyModel=/heavyEffort= are invocation flags; set lightModel/lightEffort,",
  "mediumModel/mediumEffort and the optional <tier>FallbackModel/<tier>FallbackEffort",
  "with /pr-review-config. A fallback never inherits from another tier.",
  "Strict evidence checks and an isolated adjudication pass validate/deduplicate candidates.",
  "Select validated findings in the host UI, or use --all. Selection never authorizes posting.",
  "A host with no UI at all reports unavailable for each decision the invocation did not settle, so --all",
  "--comment still publishes there, while safeguard approval stays unavailable whatever the posting flags",
  "say. --unattended refuses a run that left any of them unsettled, up front, before it costs anything.",
  "--comment authorizes the proposal; --no-comment suppresses posting. The flags conflict.",
  "Without either flag, the effective saved autoPostReviews applies; it defaults to false and then requires final confirmation.",
  "Authorized selections submit a code-built COMMENT review after fresh head/lifecycle/anchor checks.",
  "Draft/closed/merged PRs cannot receive the current inline payload. Uncertain writes are never retried.",
  "Results are retained only in the originating local session; a new review replaces the previous result.",
  "publish is a new explicit authorization; retained flags, configuration and confirmations authorize nothing.",
  "It refetches the reviewed evidence and reruns every gate, and refuses repeats of published or unresolved writes.",
  "Project safeguards are discovered under --verify, presented with their source, and run only if you approve them.",
  "Validation also uses Copilot credits; publish uses none.",
  "Other review flags are not supported yet.",
].join("\n");

// Which help text an invocation is asking for, or undefined when it is not
// asking for one. `extension.mjs` does nothing but call this, so the choice is
// checked by a controlled suite rather than by a runtime probe that needs an
// installed plugin and a CLI path.
//
// Whitespace is normalised because `help  --all` is the same question as
// `help --all`, and an exact-match dispatch would answer the first with
// "Unsupported arguments". Anything else returns undefined and stays somebody
// else's command: `help me` is an unsupported argument, not a silent success.
export function helpTextFor(args) {
  const [first, second, ...rest] = String(args ?? "").trim().split(/\s+/).filter(Boolean);
  if (rest.length || (first !== "help" && first !== "--help")) return undefined;
  if (second === undefined) return helpOrientation;
  return second === "--all" || second === "all" ? helpReference : undefined;
}
